apiVersion: apps/v1

kind: Deployment

metadata:
  name: deployment

  labels:
    app: my-app

spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: abhiraj
        image: abhiraj29/prabhi
        ports: 
        - containerPort: 8000